version: "3"
services:
  db:
    image: postgres
    environment:
        POSTGRES_PASSWORD: password123
        POSTGRES_USER: user123
        POSTGRES_DB: db123
  app:
    image: sreality-app
    ports:
      - "8080:3001"